import {
  LucideIcon,
  ArrowRight,
  ArrowLeft,
  Loader2,
  Share,
  Pencil,
  User,
  Trash,
  Globe,
  MailCheck,
  Phone,
  MapPin,
  Facebook,
  X,
  Instagram,
  Youtube,
  Twitch,
  Music,
} from "lucide-react";

export const Icons: { [key: string]: LucideIcon } = {
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  loader: Loader2,
  share: Share,
  edit: Pencil,
  user: User,
  trash: Trash,
  website: Globe,
  email: MailCheck,
  phone: Phone,
  location: MapPin,
  facebook: Facebook,
  x: X,
  instagram: Instagram,
  youtube: Youtube,
  twitch: Twitch,
  youtubeMusic: Music,
  spotify: Music,
  appleMusic: Music,
  soundcloud: Music,
  deezer: Music,
  vimeo: Music,
};
